// <auto-generated />
using System;
using FkcScoring.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FkcScoring.Core.Data.Migrations
{
    [DbContext(typeof(FkcScoringContext))]
    [Migration("20260903103807_AddAiresAndDropCombatAire")]
    partial class AddAiresAndDropCombatAire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Aire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Aires");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntiteType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("TEXT");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Utilisateur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discipline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DureeCombatSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GradeMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeMin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NbJugesKata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PoidsMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("PoidsMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Sexe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Classement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Medaille")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Classements");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Combat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArbitreNom")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompetiteurAkaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompetiteurAoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DureeReelleSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstBye")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstRepechage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeDecision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Moitie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProchainCombatCouleur")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProchainCombatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreAka")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreAo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenshuCouleur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableauId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VainqueurCouleur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetiteurAkaId");

                    b.HasIndex("CompetiteurAoId");

                    b.HasIndex("ProchainCombatId");

                    b.HasIndex("TableauId");

                    b.ToTable("Combats");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeCombatDefautSec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EcartVictoire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbJugesKataDefaut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsIppon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsWazaAri")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsYuko")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reglement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeuilPoulePuisElimination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeuilPouleUnique")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ClubId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.EquipeMembre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("EquipeMembres");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.EvenementCombat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Couleur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Penalite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TempsCombat")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.ToTable("EvenementsCombat");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Kata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Katas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "Heian Shodan"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "Heian Nidan"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Nom = "Heian Sandan"
                        },
                        new
                        {
                            Id = 4,
                            Actif = true,
                            Nom = "Heian Yondan"
                        },
                        new
                        {
                            Id = 5,
                            Actif = true,
                            Nom = "Heian Godan"
                        },
                        new
                        {
                            Id = 6,
                            Actif = true,
                            Nom = "Tekki Shodan"
                        },
                        new
                        {
                            Id = 7,
                            Actif = true,
                            Nom = "Tekki Nidan"
                        },
                        new
                        {
                            Id = 8,
                            Actif = true,
                            Nom = "Tekki Sandan"
                        },
                        new
                        {
                            Id = 9,
                            Actif = true,
                            Nom = "Bassai Dai"
                        },
                        new
                        {
                            Id = 10,
                            Actif = true,
                            Nom = "Bassai Sho"
                        },
                        new
                        {
                            Id = 11,
                            Actif = true,
                            Nom = "Kanku Dai"
                        },
                        new
                        {
                            Id = 12,
                            Actif = true,
                            Nom = "Kanku Sho"
                        },
                        new
                        {
                            Id = 13,
                            Actif = true,
                            Nom = "Empi"
                        },
                        new
                        {
                            Id = 14,
                            Actif = true,
                            Nom = "Jion"
                        },
                        new
                        {
                            Id = 15,
                            Actif = true,
                            Nom = "Jitte"
                        },
                        new
                        {
                            Id = 16,
                            Actif = true,
                            Nom = "Hangetsu"
                        },
                        new
                        {
                            Id = 17,
                            Actif = true,
                            Nom = "Gankaku"
                        },
                        new
                        {
                            Id = 18,
                            Actif = true,
                            Nom = "Nijushiho"
                        },
                        new
                        {
                            Id = 19,
                            Actif = true,
                            Nom = "Chinte"
                        },
                        new
                        {
                            Id = 20,
                            Actif = true,
                            Nom = "Sochin"
                        },
                        new
                        {
                            Id = 21,
                            Actif = true,
                            Nom = "Meikyo"
                        },
                        new
                        {
                            Id = 22,
                            Actif = true,
                            Nom = "Unsu"
                        },
                        new
                        {
                            Id = 23,
                            Actif = true,
                            Nom = "Wankan"
                        },
                        new
                        {
                            Id = 24,
                            Actif = true,
                            Nom = "Jiin"
                        });
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.KataConfrontation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Equipe1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Equipe2Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstBye")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstRepechage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kata1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kata2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Moitie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbJuges")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Participant1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Participant2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProchainConfrontationCouleur")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProchainConfrontationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableauId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VainqueurCouleur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Equipe1Id");

                    b.HasIndex("Equipe2Id");

                    b.HasIndex("Kata1Id");

                    b.HasIndex("Kata2Id");

                    b.HasIndex("Participant1Id");

                    b.HasIndex("Participant2Id");

                    b.HasIndex("ProchainConfrontationId");

                    b.HasIndex("TableauId");

                    b.ToTable("KataConfrontations");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroLicence")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PoidsKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Tableau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AireId");

                    b.HasIndex("CategorieId");

                    b.ToTable("Tableaux");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.VoteJuge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfrontationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JugeNumero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteCouleur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfrontationId");

                    b.ToTable("VotesJuges");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Aire", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Categorie", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Competition", "Competition")
                        .WithMany("Categories")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Classement", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FkcScoring.Core.Data.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId");

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.Navigation("Categorie");

                    b.Navigation("Equipe");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Combat", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "CompetiteurAka")
                        .WithMany()
                        .HasForeignKey("CompetiteurAkaId");

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "CompetiteurAo")
                        .WithMany()
                        .HasForeignKey("CompetiteurAoId");

                    b.HasOne("FkcScoring.Core.Data.Entities.Combat", "ProchainCombat")
                        .WithMany()
                        .HasForeignKey("ProchainCombatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FkcScoring.Core.Data.Entities.Tableau", "Tableau")
                        .WithMany("Combats")
                        .HasForeignKey("TableauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetiteurAka");

                    b.Navigation("CompetiteurAo");

                    b.Navigation("ProchainCombat");

                    b.Navigation("Tableau");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Equipe", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Categorie", "Categorie")
                        .WithMany("Equipes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FkcScoring.Core.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.Navigation("Categorie");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.EquipeMembre", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Equipe", "Equipe")
                        .WithMany("Membres")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.EvenementCombat", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Combat", "Combat")
                        .WithMany("Evenements")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Inscription", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Categorie", "Categorie")
                        .WithMany("Inscriptions")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FkcScoring.Core.Data.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId");

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.Navigation("Categorie");

                    b.Navigation("Equipe");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.KataConfrontation", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Equipe", "Equipe1")
                        .WithMany()
                        .HasForeignKey("Equipe1Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.Equipe", "Equipe2")
                        .WithMany()
                        .HasForeignKey("Equipe2Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.Kata", "Kata1")
                        .WithMany()
                        .HasForeignKey("Kata1Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.Kata", "Kata2")
                        .WithMany()
                        .HasForeignKey("Kata2Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "Participant1")
                        .WithMany()
                        .HasForeignKey("Participant1Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.Participant", "Participant2")
                        .WithMany()
                        .HasForeignKey("Participant2Id");

                    b.HasOne("FkcScoring.Core.Data.Entities.KataConfrontation", "ProchainConfrontation")
                        .WithMany()
                        .HasForeignKey("ProchainConfrontationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FkcScoring.Core.Data.Entities.Tableau", "Tableau")
                        .WithMany("KataConfrontations")
                        .HasForeignKey("TableauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe1");

                    b.Navigation("Equipe2");

                    b.Navigation("Kata1");

                    b.Navigation("Kata2");

                    b.Navigation("Participant1");

                    b.Navigation("Participant2");

                    b.Navigation("ProchainConfrontation");

                    b.Navigation("Tableau");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Participant", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Tableau", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.Aire", "Aire")
                        .WithMany()
                        .HasForeignKey("AireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FkcScoring.Core.Data.Entities.Categorie", "Categorie")
                        .WithMany("Tableaux")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aire");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.VoteJuge", b =>
                {
                    b.HasOne("FkcScoring.Core.Data.Entities.KataConfrontation", "Confrontation")
                        .WithMany("Votes")
                        .HasForeignKey("ConfrontationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confrontation");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Categorie", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Inscriptions");

                    b.Navigation("Tableaux");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Combat", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Competition", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Equipe", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.KataConfrontation", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FkcScoring.Core.Data.Entities.Tableau", b =>
                {
                    b.Navigation("Combats");

                    b.Navigation("KataConfrontations");
                });
#pragma warning restore 612, 618
        }
    }
}
